--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.2

-- Started on 2025-06-13 16:28:56

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE gamificacion_uja;
--
-- TOC entry 4920 (class 1262 OID 16579)
-- Name: gamificacion_uja; Type: DATABASE; Schema: -; Owner: gamificacion_user
--

CREATE DATABASE gamificacion_uja WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'es-ES';


ALTER DATABASE gamificacion_uja OWNER TO gamificacion_user;

\connect gamificacion_uja

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 16594)
-- Name: alumno; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.alumno (
    dni character varying(255) NOT NULL,
    primer_apellido character varying(255),
    segundo_apellido character varying(255),
    nombre character varying(255),
    plan_del_alumno character varying(255),
    correo1 character varying(255),
    insignias integer,
    nivel integer,
    puntos integer,
    curso character varying(255),
    correo character varying(255),
    nivel_id bigint,
    profesor_id bigint,
    password character varying(255),
    rol character varying(255),
    CONSTRAINT alumno_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'PROFESOR'::character varying, 'ALUMNO'::character varying])::text[])))
);


ALTER TABLE public.alumno OWNER TO gamificacion_user;

--
-- TOC entry 221 (class 1259 OID 24823)
-- Name: alumno_insignia; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.alumno_insignia (
    id bigint NOT NULL,
    fecha_asignacion timestamp(6) without time zone,
    alumno_dni character varying(255) NOT NULL,
    insignia_id bigint NOT NULL,
    motivo character varying(250),
    dni_alumno character varying(30) NOT NULL
);


ALTER TABLE public.alumno_insignia OWNER TO gamificacion_user;

--
-- TOC entry 220 (class 1259 OID 24822)
-- Name: alumno_insignia_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.alumno_insignia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumno_insignia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 49489)
-- Name: alumnos_insignias; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.alumnos_insignias (
    id bigint NOT NULL,
    fecha_otorgacion timestamp(6) without time zone NOT NULL,
    dni_alumno character varying(255) NOT NULL,
    insignia_id bigint NOT NULL
);


ALTER TABLE public.alumnos_insignias OWNER TO gamificacion_user;

--
-- TOC entry 229 (class 1259 OID 49488)
-- Name: alumnos_insignias_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.alumnos_insignias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumnos_insignias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 24829)
-- Name: insignia; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.insignia (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL,
    puntos integer NOT NULL,
    tipo character varying(20) NOT NULL,
    actividad character varying(20) NOT NULL,
    valor integer DEFAULT 0 NOT NULL,
    CONSTRAINT insignia_actividad_check CHECK (((actividad)::text = ANY ((ARRAY['PIZARRA'::character varying, 'PREGUNTA'::character varying, 'TEST'::character varying, 'EJERCICIO'::character varying])::text[])))
);


ALTER TABLE public.insignia OWNER TO gamificacion_user;

--
-- TOC entry 222 (class 1259 OID 24828)
-- Name: insignia_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.insignia ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insignia_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 49495)
-- Name: insignias; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.insignias (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    rango_max integer,
    rango_min integer,
    tipo_actividad character varying(255) NOT NULL,
    valor integer NOT NULL,
    alumno_dni character varying(255)
);


ALTER TABLE public.insignias OWNER TO gamificacion_user;

--
-- TOC entry 231 (class 1259 OID 49494)
-- Name: insignias_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.insignias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insignias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 49619)
-- Name: nivel; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.nivel (
    id bigint NOT NULL,
    nombre character varying(255) NOT NULL,
    puntos_maximos integer NOT NULL,
    puntos_minimos integer NOT NULL
);


ALTER TABLE public.nivel OWNER TO gamificacion_user;

--
-- TOC entry 233 (class 1259 OID 49618)
-- Name: nivel_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.nivel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.nivel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 49632)
-- Name: password_reset_token; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.password_reset_token (
    id bigint NOT NULL,
    expiry_date timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    alumno_dni character varying(255) NOT NULL
);


ALTER TABLE public.password_reset_token OWNER TO gamificacion_user;

--
-- TOC entry 236 (class 1259 OID 49631)
-- Name: password_reset_token_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.password_reset_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 33059)
-- Name: profesor; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.profesor (
    id bigint NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    rol character varying(20) NOT NULL,
    usuario character varying(30) NOT NULL
);


ALTER TABLE public.profesor OWNER TO gamificacion_user;

--
-- TOC entry 224 (class 1259 OID 33058)
-- Name: profesor_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.profesor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profesor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 24808)
-- Name: profesores; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.profesores (
    id bigint NOT NULL,
    apellidos character varying(255),
    dni character varying(255),
    email character varying(255) NOT NULL,
    nombre character varying(255),
    password character varying(255) NOT NULL,
    usuario character varying(255) NOT NULL,
    contrasena character varying(255),
    correo_uja character varying(255),
    rol character varying(255),
    CONSTRAINT profesores_rol_check CHECK (((rol)::text = ANY ((ARRAY['ADMIN'::character varying, 'PROFESOR'::character varying, 'ALUMNO'::character varying])::text[])))
);


ALTER TABLE public.profesores OWNER TO gamificacion_user;

--
-- TOC entry 218 (class 1259 OID 24807)
-- Name: profesores_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.profesores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profesores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 33067)
-- Name: usuario; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    dni character varying(30),
    nombre character varying(50),
    primer_apellido character varying(50),
    rol character varying(255) NOT NULL,
    segundo_apellido character varying(50)
);


ALTER TABLE public.usuario OWNER TO gamificacion_user;

--
-- TOC entry 226 (class 1259 OID 33066)
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: gamificacion_user
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 33074)
-- Name: usuario_roles; Type: TABLE; Schema: public; Owner: gamificacion_user
--

CREATE TABLE public.usuario_roles (
    usuario_id bigint NOT NULL,
    role character varying(255)
);


ALTER TABLE public.usuario_roles OWNER TO gamificacion_user;

--
-- TOC entry 235 (class 1259 OID 49626)
-- Name: view_alumnos_completo; Type: VIEW; Schema: public; Owner: gamificacion_user
--

CREATE VIEW public.view_alumnos_completo AS
 SELECT a.dni,
    a.primer_apellido,
    a.segundo_apellido,
    a.nombre,
    a.plan_del_alumno,
    a.correo1 AS correo_electronico,
    COALESCE(ci.cantidad_insignias, (0)::bigint) AS cantidad_insignias,
    COALESCE(sp.puntos, (0)::bigint) AS puntos,
    COALESCE(n.nombre, ''::character varying) AS nivel_nombre,
    a.curso
   FROM (((public.alumno a
     LEFT JOIN ( SELECT ai.alumno_dni AS dni,
            count(*) AS cantidad_insignias
           FROM public.alumno_insignia ai
          GROUP BY ai.alumno_dni) ci ON (((a.dni)::text = (ci.dni)::text)))
     LEFT JOIN ( SELECT ai.alumno_dni AS dni,
            sum(i.valor) AS puntos
           FROM (public.alumno_insignia ai
             JOIN public.insignia i ON ((ai.insignia_id = i.id)))
          GROUP BY ai.alumno_dni) sp ON (((a.dni)::text = (sp.dni)::text)))
     LEFT JOIN public.nivel n ON (((sp.puntos >= n.puntos_minimos) AND (sp.puntos <= n.puntos_maximos))));


ALTER VIEW public.view_alumnos_completo OWNER TO gamificacion_user;

--
-- TOC entry 4895 (class 0 OID 16594)
-- Dependencies: 217
-- Data for Name: alumno; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.alumno (dni, primer_apellido, segundo_apellido, nombre, plan_del_alumno, correo1, insignias, nivel, puntos, curso, correo, nivel_id, profesor_id, password, rol) FROM stdin;
77383574M	BOLÍVAR	GARCÍA	MIGUEL	133A - Grado en Ingeniería informática	mbg00066@red.ujaen.es	\N	\N	\N	2024-25	mbg00066@red.ujaen.es	\N	\N	\N	ALUMNO
77645037G	CALDERÓN	SUÁREZ	CARLOTA	133A - Grado en Ingeniería informática	ccs00064@red.ujaen.es	\N	\N	\N	2024-25	ccs00064@red.ujaen.es	\N	\N	\N	ALUMNO
78282932V	CANO	CUBILLO	LUCÍA	133A - Grado en Ingeniería informática	lcc00116@red.ujaen.es	\N	\N	\N	2024-25	lcc00116@red.ujaen.es	\N	\N	\N	ALUMNO
NIF  - 77690485G	FERNÁNDEZ	ESPEJO	DAVID	133A - Grado en Ingeniería informática	dfe00004@red.ujaen.es	\N	\N	\N	2024-25	dfe00004@red.ujaen.es	\N	\N	\N	ALUMNO
77687961X	FUENTES	FERNÁNDEZ	MARIO	133A - Grado en Ingeniería informática	mff00020@red.ujaen.es	\N	\N	\N	2024-25	mff00020@red.ujaen.es	\N	\N	\N	ALUMNO
78241704M	GÓMEZ	FRIEYRO	MIGUEL	133A - Grado en Ingeniería informática	mgf00050@red.ujaen.es	\N	\N	\N	2024-25	mgf00050@red.ujaen.es	\N	\N	\N	ALUMNO
20997246V	GUIRADO	RODRIGUEZ	EVA	133A - Grado en Ingeniería informática	egr000 44@red.ujaen.es	\N	\N	\N	2024-25	egr000 44@red.ujaen.es	\N	\N	\N	ALUMNO
77370811F	HUESA	GUARDIOLA	CARMEN	133A - Grado en Ingeniería informática	chg00016@red.ujaen.es	\N	\N	\N	2024-25	chg00016@red.ujaen.es	\N	\N	\N	ALUMNO
78160743G	JAÉN	MARTÍNEZ	MIGUEL ÁNGEL	133A - Grado en Ingeniería informática	majm0013@red.ujaen.es	\N	\N	\N	2024-25	majm0013@red.ujaen.es	\N	\N	\N	ALUMNO
77139144L	JIMENEZ	PELAYO	CARLOS	133A - Grado en Ingeniería informática	cjp00017@red.ujaen.es	\N	\N	\N	2024-25	cjp00017@red.ujaen.es	\N	\N	\N	ALUMNO
31020476P	JIMÉNEZ	ROMERO	JAIME	133A - Grado en Ingeniería informática	jjr00025@red.ujaen.es	\N	\N	\N	2024-25	jjr00025@red.ujaen.es	\N	\N	\N	ALUMNO
53925889C	JIMÉNEZ	SÁNCHEZ	ALBA	133A - Grado en Ingeniería informática	ajs00029@red.ujaen.es	\N	\N	\N	2024-25	ajs00029@red.ujaen.es	\N	\N	\N	ALUMNO
DID - CHD902979	JURKIEWICZ		JAKUB	MIE1 - Programa Sócrates / Erasmus	jj000016@red.ujaen.es	\N	\N	\N	2024-25	jj000016@red.ujaen.es	\N	\N	\N	ALUMNO
NIE - X7805971R	KULCHENKO		DANYLO	133A - Grado en Ingeniería informática	dk000029@red.ujaen.es	\N	\N	\N	2024-25	dk000029@red.ujaen.es	\N	\N	\N	ALUMNO
77388023S	LARA	GAITÁN	JAVIER	133A - Grado en Ingeniería informática	jlg00063@red.ujaen.es	\N	\N	\N	2024-25	jlg00063@red.ujaen.es	\N	\N	\N	ALUMNO
21028026T	LEON	PULIDO	ANA	133A - Grado en Ingeniería informática	alpulido@ujaen.es	\N	\N	\N	2024-25	alpulido@ujaen.es	\N	\N	\N	ALUMNO
77380823Z	LHAOUCHI	BRIKI	MEHDI	133A - Grado en Ingeniería informática	mlb00044@red.ujaen.es	\N	\N	\N	2024-25	mlb00044@red.ujaen.es	\N	\N	\N	ALUMNO
26529995R	LIÉBANA	BELTRÁN	MIGUEL	133A - Grado en Ingeniería informática	mlb00033@red.ujaen.es	\N	\N	\N	2024-25	mlb00033@red.ujaen.es	\N	\N	\N	ALUMNO
77384546B	LIÉBANA	CRUZ	MANUEL RAFAEL	133A - Grado en Ingeniería informática	mrlc0006@red.ujaen.es	\N	\N	\N	2024-25	mrlc0006@red.ujaen.es	\N	\N	\N	ALUMNO
NIE - X5781443W	LIN		HAORI	133A - Grado en Ingeniería informática	hrl00001@red.ujaen.es	\N	\N	\N	2024-25	hrl00001@red.ujaen.es	\N	\N	\N	ALUMNO
77378445M	LÓPEZ	LARA	JOSÉ ANTONIO	133A - Grado en Ingeniería informática	jall0012@red.ujaen.es	\N	\N	\N	2024-25	jall0012@red.ujaen.es	\N	\N	\N	ALUMNO
75576914H	LÓPEZ	MORALES	DANIEL	133A - Grado en Ingeniería informática	dlm00045@red.ujaen.es	\N	\N	\N	2024-25	dlm00045@red.ujaen.es	\N	\N	\N	ALUMNO
26925402S	LORENTE	WAGNER	DAVID	133A - Grado en Ingeniería informática	dlw00001@red.ujaen.es	\N	\N	\N	2024-25	dlw00001@red.ujaen.es	\N	\N	\N	ALUMNO
NIE - X9996665Z	MANAKKIL	THOMAN	GODWIN GONESALAS	133A - Grado en Ingeniería informática	ggmt0001@red.ujaen.es	\N	\N	\N	2024-25	ggmt0001@red.ujaen.es	\N	\N	\N	ALUMNO
26534206A	MARÍN	PADILLA	LUCÍA	133A - Grado en Ingeniería informática	lmp00072@red.ujaen.es	\N	\N	\N	2024-25	lmp00072@red.ujaen.es	\N	\N	\N	ALUMNO
77384796P	MARTÍNEZ	GONZÁLEZ	JAVIER	133A - Grado en Ingeniería informática	jmg00144@red.ujaen.es	\N	\N	\N	2024-25	jmg00144@red.ujaen.es	\N	\N	\N	ALUMNO
26509109E	MARTÍNEZ	JIMÉNEZ	JOSÉ RAMÓN	133A - Grado en Ingeniería informática	jrmj0001@red.ujaen.es	\N	\N	\N	2024-25	jrmj0001@red.ujaen.es	\N	\N	\N	ALUMNO
77688419P	MARTÍNEZ	LOMAS	FRANCISCO JAVIER	133A - Grado en Ingeniería informática	fjml0023@red.ujaen.es	\N	\N	\N	2024-25	fjml0023@red.ujaen.es	\N	\N	\N	ALUMNO
77433807Y	MARTÍNEZ	MARTÍNEZ	TITO	133A - Grado en Ingeniería informática	tmm00029@red.ujaen.es	\N	\N	\N	2024-25	tmm00029@red.ujaen.es	\N	\N	\N	ALUMNO
75939553Q	MARTÍNEZ	RODRÍGUEZ	DAVID	133A - Grado en Ingeniería informática	dmr00065@red.ujaen.es	\N	\N	\N	2024-25	dmr00065@red.ujaen.es	\N	\N	\N	ALUMNO
77768881Q	MARTÍNEZ	TRISTANTE	PALOMA MARÍA	133A - Grado en Ingeniería informática	pmmt0001@red.ujaen.es	\N	\N	\N	2024-25	pmmt0001@red.ujaen.es	\N	\N	\N	ALUMNO
26507568E	MARTOS	CUEVAS	JUAN	133A - Grado en Ingeniería informática	jmc00187@red.ujaen.es	\N	\N	\N	2024-25	jmc00187@red.ujaen.es	\N	\N	\N	ALUMNO
77693489H	MARTOS	DÍEZ	ÁLVARO	133A - Grado en Ingeniería informática	amd00043@red.ujaen.es	\N	\N	\N	2024-25	amd00043@red.ujaen.es	\N	\N	\N	ALUMNO
78026126Y	MATA	ARMERO	JAVIER	133A - Grado en Ingeniería informática	jma00082@red.ujaen.es	\N	\N	\N	2024-25	jma00082@red.ujaen.es	\N	\N	\N	ALUMNO
77647203P	MEDIANO	MARTÍNEZ	PABLO	133A - Grado en Ingeniería informática	pmm00107@red.ujaen.es	\N	\N	\N	2024-25	pmm00107@red.ujaen.es	\N	\N	\N	ALUMNO
51212285W	MELERO	MONTERO	GABRIEL	133A - Grado en Ingeniería informática	gmm00051@red.ujaen.es	\N	\N	\N	2024-25	gmm00051@red.ujaen.es	\N	\N	\N	ALUMNO
77380455Z	MÉNDEZ	ORTEGA	JESÚS	133A - Grado en Ingeniería informática	jmo00033@red.ujaen.es	\N	\N	\N	2024-25	jmo00033@red.ujaen.es	\N	\N	\N	ALUMNO
77692711E	MESA	MESA	FRANCISCO	133A - Grado en Ingeniería informática	fmm00085@red.ujaen.es	\N	\N	\N	2024-25	fmm00085@red.ujaen.es	\N	\N	\N	ALUMNO
78015840R	MONTERROSO	CABALLERO	ANTONIO	133A - Grado en Ingeniería informática	amc00345@red.ujaen.es	\N	\N	\N	2024-25	amc00345@red.ujaen.es	\N	\N	\N	ALUMNO
46096933B	MONTES	TRUJILLO	JUAN	133A - Grado en Ingeniería informática	jmt00043@red.ujaen.es	\N	\N	\N	2024-25	jmt00043@red.ujaen.es	\N	\N	\N	ALUMNO
77693988B	MONTORO	BERMÚDEZ	PABLO JAVIER	133A - Grado en Ingeniería informática	pjmb0003@red.ujaen.es	\N	\N	\N	2024-25	pjmb0003@red.ujaen.es	\N	\N	\N	ALUMNO
77688439M	MONZÓN	VÁZQUEZ	MODESTO	133A - Grado en Ingeniería informática	mmonzon@ujaen.es	\N	\N	\N	2024-25	mmonzon@ujaen.es	\N	\N	\N	ALUMNO
77432166K	MORAL	NAVARRO	JAVIER DEL	133A - Grado en Ingeniería informática	jmn00023@red.ujaen.es	\N	\N	\N	2024-25	jmn00023@red.ujaen.es	\N	\N	\N	ALUMNO
26583240R	ARELLANO	JIMÉNEZ	TOMÁS JESÚS	133A - Grado en Ingeniería informática	tjaj0001@red.ujaen.es	\N	\N	\N	2024-25	tjaj0001@red.ujaen.es	\N	\N	\N	ALUMNO
26959126K	MORENO	CABELLO	CÉSAR	133A - Grado en Ingeniería informática	cmc00150@red.ujaen.es	\N	\N	\N	2024-25	cmc00150@red.ujaen.es	\N	\N	\N	ALUMNO
26529270N	MUÑOZ	MILLÁN	SAMUEL	133A - Grado en Ingeniería informática	smm00156@red.ujaen.es	\N	\N	\N	2024-25	smm00156@red.ujaen.es	\N	\N	\N	ALUMNO
77690672F	MUROS	MELERO	JOSÉ MANUEL	133A - Grado en Ingeniería informática	jmmm0082@red.ujaen.es	\N	\N	\N	2024-25	jmmm0082@red.ujaen.es	\N	\N	\N	ALUMNO
77385608S	NAVAS	POUSIBET	ESPERANZA	133A - Grado en Ingeniería informática	enp00009@red.ujaen.es	\N	\N	\N	2024-25	enp00009@red.ujaen.es	\N	\N	\N	ALUMNO
77382170G	ORDÓÑEZ	QUIRÓS	CRISTINA	133A - Grado en Ingeniería informática	coq00002@red.ujaen.es	\N	\N	\N	2024-25	coq00002@red.ujaen.es	\N	\N	\N	ALUMNO
78161920P	ORTEGA	PEINADO	IGNACIO	133A - Grado en Ingeniería informática	iop00011@red.ujaen.es	\N	\N	\N	2024-25	iop00011@red.ujaen.es	\N	\N	\N	ALUMNO
31024321N	OSUNA	VENTURA	RAFAEL	133A - Grado en Ingeniería informática	rov00005@red.ujaen.es	\N	\N	\N	2024-25	rov00005@red.ujaen.es	\N	\N	\N	ALUMNO
77645017F	PADILLA	LEÓN	MANUEL JESÚS	133A - Grado en Ingeniería informática	mjpl0013@red.ujaen.es	\N	\N	\N	2024-25	mjpl0013@red.ujaen.es	\N	\N	\N	ALUMNO
77644234Y	PAREDES	BORJA	MARCO	133A - Grado en Ingeniería informática	mpb00053@red.ujaen.es	\N	\N	\N	2024-25	mpb00053@red.ujaen.es	\N	\N	\N	ALUMNO
78227231E	PARRILLA	FUENTES	JOSE LUIS	133A - Grado en Ingeniería informática	jlpf0006@red.ujaen.es	\N	\N	\N	2024-25	jlpf0006@red.ujaen.es	\N	\N	\N	ALUMNO
54593584W	PEDRAJAS	DE LA TORRE	JOSÉ	133A - Grado en Ingeniería informática	jpt00012@red.ujaen.es	\N	\N	\N	2024-25	jpt00012@red.ujaen.es	\N	\N	\N	ALUMNO
78029254Y	PEÑA	ÁGUILA	DAVID	133A - Grado en Ingeniería informática	dpa00021@red.ujaen.es	\N	\N	\N	2024-25	dpa00021@red.ujaen.es	\N	\N	\N	ALUMNO
77434377R	PÉREZ	CASTIÑEIRA	ALBERTO	133A - Grado en Ingeniería informática	apc00141@red.ujaen.es	\N	\N	\N	2024-25	apc00141@red.ujaen.es	\N	\N	\N	ALUMNO
77433858B	PÉREZ	CHICA	RUBÉN	133A - Grado en Ingeniería informática	rpc00061@red.ujaen.es	\N	\N	\N	2024-25	rpc00061@red.ujaen.es	\N	\N	\N	ALUMNO
78162766A	PÉREZ	MOLINA	PABLO	133A - Grado en Ingeniería informática	ppm00052@red.ujaen.es	\N	\N	\N	2024-25	ppm00052@red.ujaen.es	\N	\N	\N	ALUMNO
26538835D	PÍÑAR	AMORES	AINHOA	133A - Grado en Ingeniería informática	apa00072@red.ujaen.es	\N	\N	\N	2024-25	apa00072@red.ujaen.es	\N	\N	\N	ALUMNO
78028516G	PLAZAS	CAZALILLA	ROCÍO	133A - Grado en Ingeniería informática	rpc00056@red.ujaen.es	\N	\N	\N	2024-25	rpc00056@red.ujaen.es	\N	\N	\N	ALUMNO
26536858X	PULIDO	DÍAZ	JOSÉ	133A - Grado en Ingeniería informática	jpd00010@red.ujaen.es	\N	\N	\N	2024-25	jpd00010@red.ujaen.es	\N	\N	\N	ALUMNO
26503296M	QUIRÓS	COBO	PABLO	133A - Grado en Ingeniería informática	pqc00002@red.ujaen.es	\N	\N	\N	2024-25	pqc00002@red.ujaen.es	\N	\N	\N	ALUMNO
77384763K	RAMÍREZ	DÍAZ	ÁLVARO	133A - Grado en Ingeniería informática	ard00032@red.ujaen.es	\N	\N	\N	2024-25	ard00032@red.ujaen.es	\N	\N	\N	ALUMNO
77645228B	ROBLES	CARAZO	MIGUEL	133A - Grado en Ingeniería informática	mrc00135@red.ujaen.es	\N	\N	\N	2024-25	mrc00135@red.ujaen.es	\N	\N	\N	ALUMNO
21025618F	RODELAS	DELGADO	ADRIÁN	133A - Grado en Ingeniería informática	ard00037@red.ujaen.es	\N	\N	\N	2024-25	ard00037@red.ujaen.es	\N	\N	\N	ALUMNO
75938011S	RODRÍGUEZ	SABIO	CRISTIAN	133A - Grado en Ingeniería informática	crs00047@red.ujaen.es	\N	\N	\N	2024-25	crs00047@red.ujaen.es	\N	\N	\N	ALUMNO
77692498Q	ROJAS	GARCÍA	ALEJANDRO	133A - Grado en Ingeniería informática	arg00184@red.ujaen.es	\N	\N	\N	2024-25	arg00184@red.ujaen.es	\N	\N	\N	ALUMNO
7811423 3T	ROJAS	ROJAS	DIEGO	133A - Grado en Ingeniería informática	rrr00053@red.ujaen.es	\N	\N	\N	2024-25	rrr00053@red.ujaen.es	\N	\N	\N	ALUMNO
NIE - Y7970158M	ROSA	FIEDLER	MAITENA MARIA	133A - Grado en Ingeniería informática	mmrf0008@red.ujaen.es	\N	\N	\N	2024-25	mmrf0008@red.ujaen.es	\N	\N	\N	ALUMNO
26584978Z	RUIZ	AGLIO	PEDRO	133A - Grado en Ingeniería informática	pra00020@red.ujaen.es	\N	\N	\N	2024-25	pra00020@red.ujaen.es	\N	\N	\N	ALUMNO
53919918Y	RUIZ	BLANCO	CARLOS ALBERTO	133A - Grado en Ingeniería informática	carb0003@red.ujaen.es	\N	\N	\N	2024-25	carb0003@red.ujaen.es	\N	\N	\N	ALUMNO
26519975D	RUIZ	LOZANO	ISAAC	133A - Grado en Ingeniería informática	irl00030@red.ujaen.es	\N	\N	\N	2024-25	irl00030@red.ujaen.es	\N	\N	\N	ALUMNO
77145701K	RUIZ	MARTÍN	RODRIGO	133A - Grado en Ingeniería informática	rrm00082@red.ujaen.es	\N	\N	\N	2024-25	rrm00082@red.ujaen.es	\N	\N	\N	ALUMNO
26508254H	RUIZ	PELÁEZ	JAVIER	133A - Grado en Ingeniería informática	jrp00058@red.ujaen.es	\N	\N	\N	2024-25	jrp00058@red.ujaen.es	\N	\N	\N	ALUMNO
78026682X	RUIZ	QUESADA	DARÍO	133A - Grado en Ingeniería informática	drq00002@red.ujaen.es	\N	\N	\N	2024-25	drq00002@red.ujaen.es	\N	\N	\N	ALUMNO
75575876S	SÁEZ	BARRALES	RAMÓN	133A - Grado en Ingeniería informática	rsb00021@red.ujaen.es	\N	\N	\N	2024-25	rsb00021@red.ujaen.es	\N	\N	\N	ALUMNO
74544143Q	SÁNCHEZ	GARCÍA	ANTONIO	133A - Grado en Ingeniería informática	asg00156@red.ujaen.es	\N	\N	\N	2024-25	asg00156@red.ujaen.es	\N	\N	\N	ALUMNO
45925010J	SANTOS	DENGRA	ÁLVARO	133A - Grado en Ingeniería informática	asd00028@red.ujaen.es	\N	\N	\N	2024-25	asd00028@red.ujaen.es	\N	\N	\N	ALUMNO
DID - CEY735890	SARNACKA		ANNA	MIE1 - Programa Sócrates / Erasmus	as000171@red.ujaen.es	\N	\N	\N	2024-25	as000171@red.ujaen.es	\N	\N	\N	ALUMNO
14274535E	SEGOVIA	BAENA	JAIME	133A - Grado en Ingeniería informática	jsb00025@red.ujaen.es	\N	\N	\N	2024-25	jsb00025@red.ujaen.es	\N	\N	\N	ALUMNO
78161710M	SERRANO	DURÁN	MANUEL	133A - Grado en Ingeniería informática	msd00023@red.ujaen.es	\N	\N	\N	2024-25	msd00023@red.ujaen.es	\N	\N	\N	ALUMNO
21037276G	SEVILLA	LÓPEZ	JESÚS	133A - Grado en Ingeniería informática	jsl00024@red.ujaen.es	\N	\N	\N	2024-25	jsl00024@red.ujaen.es	\N	\N	\N	ALUMNO
NIE - Y9154426A	SHYBISTA		ZHANNA	133A - Grado en Ingeniería informática	zs000009@red.ujaen.es	\N	\N	\N	2024-25	zs000009@red.ujaen.es	\N	\N	\N	ALUMNO
DID - 04280308445	SOBOCINSKA		JULIA	MIE1 - Programa Sócrates / Erasmus	js000063@red.ujaen.es	\N	\N	\N	2024-25	js000063@red.ujaen.es	\N	\N	\N	ALUMNO
78163164X	TEVA	ZUHEROS	ALEJANDRO	133A - Grado en Ingeniería informática	atz00004@red.ujaen.es	\N	\N	\N	2024-25	atz00004@red.ujaen.es	\N	\N	\N	ALUMNO
77383587H	TORRES	HERRERA	GREGORIO	133A - Grado en Ingeniería informática	gth00002@red.ujaen.es	\N	\N	\N	2024-25	gth00002@red.ujaen.es	\N	\N	\N	ALUMNO
76629731X	TORTOSA	SILES	PABLO	133A - Grado en Ingeniería informática	pts00002@red.ujaen.es	\N	\N	\N	2024-25	pts00002@red.ujaen.es	\N	\N	\N	ALUMNO
14274274Z	FREGENAL	CASTRO	PABLO	133A - Grado en Ingeniería informática	pfc00020@red.ujaen.es	\N	\N	\N	2024-25	pfc00020@red.ujaen.es	\N	\N	\N	ALUMNO
26918039N	JIMÉNEZ	ANTEQUERA	ANTONIO JOSÉ	133A - Grado en Ingeniería informática	ajja0004@red.ujaen.es	\N	\N	\N	2024-25	ajja0004@red.ujaen.es	\N	\N	\N	ALUMNO
71367739G	LATORRE	MARTOS	ADRIÁN	133A - Grado en Ingeniería informática	alm00204@red.ujaen.es	\N	\N	\N	2024-25	alm00204@red.ujaen.es	\N	\N	\N	ALUMNO
26531292X	LÓPEZ	MARTÍNEZ	RAÚL	133A - Grado en Ingeniería informática	rlm00063@red.ujaen.es	\N	\N	\N	2024-25	rlm00063@red.ujaen.es	\N	\N	\N	ALUMNO
77385534X	MARTÍNEZ	HERREROS	JOSÉ LUIS	133A - Grado en Ingeniería informática	jlmh0005@red.ujaen.es	\N	\N	\N	2024-25	jlmh0005@red.ujaen.es	\N	\N	\N	ALUMNO
77147095N	MASATS	AROZA	LUCÍA	133A - Grado en Ingeniería informática	lma00072@red.ujaen.es	\N	\N	\N	2024-25	lma00072@red.ujaen.es	\N	\N	\N	ALUMNO
77377703E	MOLINA	MARTOS	ÁLVARO	133A - Grado en Ingeniería informática	amm00465@red.ujaen.es	\N	\N	\N	2024-25	amm00465@red.ujaen.es	\N	\N	\N	ALUMNO
54697199W	MORENA	ÁLVAREZ	FELIPE DE LA	133A - Grado en Ingeniería informática	fma00040@red.ujaen.es	\N	\N	\N	2024-25	fma00040@red.ujaen.es	\N	\N	\N	ALUMNO
78281126M	MORENO	ARJONA	JAVIER	133A - Grado en Ingeniería informática	jma00081@red.ujaen.es	\N	\N	\N	2024-25	jma00081@red.ujaen.es	\N	\N	\N	ALUMNO
77693547F	MUÑOZ	GALLARDO	LYDIA	133A - Grado en Ingeniería informática	lgallard@ujaen.es	\N	\N	\N	2024-25	lgallard@ujaen.es	\N	\N	\N	ALUMNO
26525147Y	PADILLA	ANULA	PABLO	133A - Grado en Ingeniería informática	ppa00019@red.ujaen.es	\N	\N	\N	2024-25	ppa00019@red.ujaen.es	\N	\N	\N	ALUMNO
20621771V	PÉREZ	CASTILLA	JESÚS	133A - Grado en Ingeniería informática	jpc00068@red.ujaen.es	\N	\N	\N	2024-25	jpc00068@red.ujaen.es	\N	\N	\N	ALUMNO
26925584J	POZAS	SERRANO	IVÁN	133A - Grado en Ingeniería inform ática	ips00024@red.ujaen.es	\N	\N	\N	2024-25	ips00024@red.ujaen.es	\N	\N	\N	ALUMNO
26255000V	RODRÍGUEZ	FERNÁNDEZ	JUAN ANTONIO	133A - Grado en Ingeniería informática	jarodrig@ujaen.es	\N	\N	\N	2024-25	jarodrig@ujaen.es	\N	\N	\N	ALUMNO
26521887N	RUIZ	FERNÁNDEZ	LÁZARO	133A - Grado en Ingeniería informática	lrf000 11@red.ujaen.es	\N	\N	\N	2024-25	lrf000 11@red.ujaen.es	\N	\N	\N	ALUMNO
15522133P	SÁNCHEZ	NÁJERA	ELENA	133A - Grado en Ingeniería informática	esn00006@red.ujaen.es	\N	\N	\N	2024-25	esn00006@red.ujaen.es	\N	\N	\N	ALUMNO
44925572V	SIERRA	PANCORBO	EDÉN	133A - Grado en Ingeniería informática	esp00018@red.ujaen.es	\N	\N	\N	2024-25	esp00018@red.ujaen.es	\N	\N	\N	ALUMNO
77372894C	ABAMBARI	COLLAGUAZO	KAMIL XAVIER	133A - Grado en Ingeniería informática	kxac0001@red.ujaen.es	\N	\N	\N	2024-25	\N	\N	\N	\N	ALUMNO
\.


--
-- TOC entry 4899 (class 0 OID 24823)
-- Dependencies: 221
-- Data for Name: alumno_insignia; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.alumno_insignia (id, fecha_asignacion, alumno_dni, insignia_id, motivo, dni_alumno) FROM stdin;
\.


--
-- TOC entry 4908 (class 0 OID 49489)
-- Dependencies: 230
-- Data for Name: alumnos_insignias; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.alumnos_insignias (id, fecha_otorgacion, dni_alumno, insignia_id) FROM stdin;
\.


--
-- TOC entry 4901 (class 0 OID 24829)
-- Dependencies: 223
-- Data for Name: insignia; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.insignia (id, nombre, puntos, tipo, actividad, valor) FROM stdin;
\.


--
-- TOC entry 4910 (class 0 OID 49495)
-- Dependencies: 232
-- Data for Name: insignias; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.insignias (id, nombre, rango_max, rango_min, tipo_actividad, valor, alumno_dni) FROM stdin;
1	Oro	\N	\N	Realizar ejercicios en pizarra	3	\N
2	Plata	\N	\N	Realizar ejercicios en pizarra	2	\N
3	Bronce	\N	\N	Realizar ejercicios en pizarra	1	\N
8	Oro	\N	\N	Responder preguntas en clase	3	\N
9	Plata	\N	\N	Responder preguntas en clase	2	\N
10	Bronce	\N	\N	Responder preguntas en clase	1	\N
11	Oro	10	9	Realizar test en platea	3	\N
12	Plata	8	7	Realizar test en platea	2	\N
13	Bronce	6	5	Realizar test en platea	1	\N
14	Oro	10	9	Realizar ejercicios evaluables/revisados por el profesor	3	\N
15	Plata	8	7	Realizar ejercicios evaluables/revisados por el profesor	2	\N
16	Bronce	6	5	Realizar ejercicios evaluables/revisados por el profesor	1	\N
\.


--
-- TOC entry 4912 (class 0 OID 49619)
-- Dependencies: 234
-- Data for Name: nivel; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.nivel (id, nombre, puntos_maximos, puntos_minimos) FROM stdin;
1	Nivel 4	200	151
2	Nivel 3	150	100
4	Nivel 2	99	5
3	Nivel 1	4	0
\.


--
-- TOC entry 4914 (class 0 OID 49632)
-- Dependencies: 237
-- Data for Name: password_reset_token; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.password_reset_token (id, expiry_date, token, alumno_dni) FROM stdin;
\.


--
-- TOC entry 4903 (class 0 OID 33059)
-- Dependencies: 225
-- Data for Name: profesor; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.profesor (id, email, password, rol, usuario) FROM stdin;
\.


--
-- TOC entry 4897 (class 0 OID 24808)
-- Dependencies: 219
-- Data for Name: profesores; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.profesores (id, apellidos, dni, email, nombre, password, usuario, contrasena, correo_uja, rol) FROM stdin;
\.


--
-- TOC entry 4905 (class 0 OID 33067)
-- Dependencies: 227
-- Data for Name: usuario; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.usuario (id, email, enabled, password, username, dni, nombre, primer_apellido, rol, segundo_apellido) FROM stdin;
10	maria.tutora@ujaen.es	t	$2a$10$rRWuyXHV4VuGCgu89.t2E.CROtvMEEVh3QIYC.Vk2ijFzfwgMB8eS	maria.tutora@ujaen.es	\N	\N	\N	ADMIN	\N
\.


--
-- TOC entry 4906 (class 0 OID 33074)
-- Dependencies: 228
-- Data for Name: usuario_roles; Type: TABLE DATA; Schema: public; Owner: gamificacion_user
--

COPY public.usuario_roles (usuario_id, role) FROM stdin;
\.


--
-- TOC entry 4922 (class 0 OID 0)
-- Dependencies: 220
-- Name: alumno_insignia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.alumno_insignia_id_seq', 1, false);


--
-- TOC entry 4923 (class 0 OID 0)
-- Dependencies: 229
-- Name: alumnos_insignias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.alumnos_insignias_id_seq', 16, true);


--
-- TOC entry 4924 (class 0 OID 0)
-- Dependencies: 222
-- Name: insignia_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.insignia_id_seq', 1, false);


--
-- TOC entry 4925 (class 0 OID 0)
-- Dependencies: 231
-- Name: insignias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.insignias_id_seq', 16, true);


--
-- TOC entry 4926 (class 0 OID 0)
-- Dependencies: 233
-- Name: nivel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.nivel_id_seq', 16, true);


--
-- TOC entry 4927 (class 0 OID 0)
-- Dependencies: 236
-- Name: password_reset_token_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.password_reset_token_id_seq', 1, true);


--
-- TOC entry 4928 (class 0 OID 0)
-- Dependencies: 224
-- Name: profesor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.profesor_id_seq', 1, false);


--
-- TOC entry 4929 (class 0 OID 0)
-- Dependencies: 218
-- Name: profesores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.profesores_id_seq', 12, true);


--
-- TOC entry 4930 (class 0 OID 0)
-- Dependencies: 226
-- Name: usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: gamificacion_user
--

SELECT pg_catalog.setval('public.usuario_id_seq', 10, true);


--
-- TOC entry 4709 (class 2606 OID 24827)
-- Name: alumno_insignia alumno_insignia_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumno_insignia
    ADD CONSTRAINT alumno_insignia_pkey PRIMARY KEY (id);


--
-- TOC entry 4699 (class 2606 OID 49476)
-- Name: alumno alumno_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumno
    ADD CONSTRAINT alumno_pkey PRIMARY KEY (dni);


--
-- TOC entry 4723 (class 2606 OID 49493)
-- Name: alumnos_insignias alumnos_insignias_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumnos_insignias
    ADD CONSTRAINT alumnos_insignias_pkey PRIMARY KEY (id);


--
-- TOC entry 4711 (class 2606 OID 24835)
-- Name: insignia insignia_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.insignia
    ADD CONSTRAINT insignia_pkey PRIMARY KEY (id);


--
-- TOC entry 4725 (class 2606 OID 49501)
-- Name: insignias insignias_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.insignias
    ADD CONSTRAINT insignias_pkey PRIMARY KEY (id);


--
-- TOC entry 4731 (class 2606 OID 49623)
-- Name: nivel nivel_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.nivel
    ADD CONSTRAINT nivel_pkey PRIMARY KEY (id);


--
-- TOC entry 4735 (class 2606 OID 49638)
-- Name: password_reset_token password_reset_token_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT password_reset_token_pkey PRIMARY KEY (id);


--
-- TOC entry 4713 (class 2606 OID 33065)
-- Name: profesor profesor_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT profesor_pkey PRIMARY KEY (id);


--
-- TOC entry 4701 (class 2606 OID 24814)
-- Name: profesores profesores_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.profesores
    ADD CONSTRAINT profesores_pkey PRIMARY KEY (id);


--
-- TOC entry 4703 (class 2606 OID 49508)
-- Name: profesores uk2pvv1tqm0byow8wujjtuyiyo7; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.profesores
    ADD CONSTRAINT uk2pvv1tqm0byow8wujjtuyiyo7 UNIQUE (correo_uja);


--
-- TOC entry 4737 (class 2606 OID 49642)
-- Name: password_reset_token uk3wthgslkljta3xl5do2gyirpu; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT uk3wthgslkljta3xl5do2gyirpu UNIQUE (alumno_dni);


--
-- TOC entry 4705 (class 2606 OID 24816)
-- Name: profesores uk48alpytkeu2ievev6tpkymd38; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.profesores
    ADD CONSTRAINT uk48alpytkeu2ievev6tpkymd38 UNIQUE (email);


--
-- TOC entry 4715 (class 2606 OID 33291)
-- Name: profesor uk76mq23iu354cf0u5ka4nkcetq; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT uk76mq23iu354cf0u5ka4nkcetq UNIQUE (usuario);


--
-- TOC entry 4719 (class 2606 OID 49504)
-- Name: usuario uk863n1y3x0jalatoir4325ehal; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk863n1y3x0jalatoir4325ehal UNIQUE (username);


--
-- TOC entry 4739 (class 2606 OID 49640)
-- Name: password_reset_token ukg0guo4k8krgpwuagos61oc06j; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT ukg0guo4k8krgpwuagos61oc06j UNIQUE (token);


--
-- TOC entry 4727 (class 2606 OID 49614)
-- Name: insignias ukkysvxg0iid6i8tjwij99xpaae; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.insignias
    ADD CONSTRAINT ukkysvxg0iid6i8tjwij99xpaae UNIQUE (tipo_actividad, nombre);


--
-- TOC entry 4733 (class 2606 OID 49625)
-- Name: nivel ukmuxtrrmyiupgv6bheiif25oqu; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.nivel
    ADD CONSTRAINT ukmuxtrrmyiupgv6bheiif25oqu UNIQUE (nombre);


--
-- TOC entry 4717 (class 2606 OID 33237)
-- Name: profesor ukn0cxx7qsaxhxjhib2aq054nip; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.profesor
    ADD CONSTRAINT ukn0cxx7qsaxhxjhib2aq054nip UNIQUE (email);


--
-- TOC entry 4707 (class 2606 OID 24818)
-- Name: profesores uktkma60cu4xhbsqtwoa6feekpj; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.profesores
    ADD CONSTRAINT uktkma60cu4xhbsqtwoa6feekpj UNIQUE (usuario);


--
-- TOC entry 4729 (class 2606 OID 49616)
-- Name: insignias uq_tipo_nombre; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.insignias
    ADD CONSTRAINT uq_tipo_nombre UNIQUE (tipo_actividad, nombre);


--
-- TOC entry 4721 (class 2606 OID 33073)
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- TOC entry 4747 (class 2606 OID 49519)
-- Name: insignias fk1kskh90lvf7ieps7vp27g49eo; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.insignias
    ADD CONSTRAINT fk1kskh90lvf7ieps7vp27g49eo FOREIGN KEY (alumno_dni) REFERENCES public.alumno(dni);


--
-- TOC entry 4741 (class 2606 OID 24849)
-- Name: alumno_insignia fk3l7k8lrhxl3sunrekokj2g31y; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumno_insignia
    ADD CONSTRAINT fk3l7k8lrhxl3sunrekokj2g31y FOREIGN KEY (insignia_id) REFERENCES public.insignia(id);


--
-- TOC entry 4745 (class 2606 OID 49514)
-- Name: alumnos_insignias fk4j20g0ppbhf0ye8b9g0snsb9y; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumnos_insignias
    ADD CONSTRAINT fk4j20g0ppbhf0ye8b9g0snsb9y FOREIGN KEY (insignia_id) REFERENCES public.insignias(id);


--
-- TOC entry 4740 (class 2606 OID 33262)
-- Name: alumno fkdqvc9m1jcf090ov39n5jfrti2; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumno
    ADD CONSTRAINT fkdqvc9m1jcf090ov39n5jfrti2 FOREIGN KEY (profesor_id) REFERENCES public.usuario(id);


--
-- TOC entry 4742 (class 2606 OID 49477)
-- Name: alumno_insignia fkh3ba8pxs4t1j35kegvtgr9603; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumno_insignia
    ADD CONSTRAINT fkh3ba8pxs4t1j35kegvtgr9603 FOREIGN KEY (alumno_dni) REFERENCES public.alumno(dni);


--
-- TOC entry 4748 (class 2606 OID 49643)
-- Name: password_reset_token fkhqcg3tc174p0bb5kxq7twa0dd; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.password_reset_token
    ADD CONSTRAINT fkhqcg3tc174p0bb5kxq7twa0dd FOREIGN KEY (alumno_dni) REFERENCES public.alumno(dni);


--
-- TOC entry 4743 (class 2606 OID 49482)
-- Name: alumno_insignia fkklk7qmd8b8yfwp2wtu0bgyyg0; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumno_insignia
    ADD CONSTRAINT fkklk7qmd8b8yfwp2wtu0bgyyg0 FOREIGN KEY (dni_alumno) REFERENCES public.alumno(dni);


--
-- TOC entry 4746 (class 2606 OID 49509)
-- Name: alumnos_insignias fkle61j69lykhg54civ8xphe3f4; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.alumnos_insignias
    ADD CONSTRAINT fkle61j69lykhg54civ8xphe3f4 FOREIGN KEY (dni_alumno) REFERENCES public.alumno(dni);


--
-- TOC entry 4744 (class 2606 OID 33083)
-- Name: usuario_roles fkqblnumndby0ftm4c7sg6uso6p; Type: FK CONSTRAINT; Schema: public; Owner: gamificacion_user
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fkqblnumndby0ftm4c7sg6uso6p FOREIGN KEY (usuario_id) REFERENCES public.usuario(id);


--
-- TOC entry 4921 (class 0 OID 0)
-- Dependencies: 5
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT CREATE ON SCHEMA public TO gamificacion_user;


--
-- TOC entry 2096 (class 826 OID 16585)
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: -; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT ALL ON TABLES TO gamificacion_user;


-- Completed on 2025-06-13 16:28:56

--
-- PostgreSQL database dump complete
--

